export const language = {
	appName: `Messenger`,
	close: `Close`,
	connect: `Connect`,
	connectorNotFound: `Connector Not Found`,
	copyAddress: `Copy Address`,
	copied: `Copied`,
	disconnect: `Disconnect`,
	fetching: `Fetching`,
	loading: `Loading`,
	message: (recipient: string) => `Message ${recipient}`,
	noMessages: `No Messages`,
	send: `Send`,
	sending: `Sending`,
	sendMessage: `Send Message`,
	groupSelect: `Group Select`,
	noGroups: `No Groups`,
	createGroup: `Create Group`,
	title: `Title`,
	submit: `Submit`,
	logo: `Logo`,
	upload: `Upload`,
	uploadImage: `Upload Image`
};
