export const language = {
	appName: `Messenger`,
	close: `Close`,
	connect: `Connect`,
	connectorNotFound: `Connector Not Found`,
	copyWalletAddress: `Copy Wallet Address`,
	copied: `Copied`,
	disconnect: `Disconnect`,
	fetching: `Fetching`,
	loading: `Loading`,
	message: (recipient: string) => `Message ${recipient}`,
	noMessages: `No Messages`,
	send: `Send`,
	sending: `Sending`,
	sendMessage: `Send Message`,
	groupSelect: `Group Select`,
	noGroups: `No Groups`,
	createGroup: `Create Group`,
	title: `Title`,
	submit: `Submit`,
	logo: `Logo`,
	upload: `Upload`,
	uploadImage: `Upload Image`,
	initialChannel: `Initial Channel`,
	errorOccurred: `Error Occurred`,
	arweaveAppConnectionError: `Connection error with Arweave.app. The connector window must remain open after the initial connection.`,
	groupCreated: `Group Created`,
	addGroupMember: `Add Group Member`,
	createChannel: `Create a Channel`,
	walletAddress: `Wallet Address`,
	channelTitle: `Channel Title`,
	channelCreated: `Channel created`,
	memberAdded: `Member Added`,
	member: `Member`,
	members: `Members`,
	viewProfile: `View Profile`,
	profile: `Profile`,
	social: `Social`,
	twitter: `Twitter`,
	discord: `Discord`,
	groupId: `Group ID`,
	groupMembers: `Group Members`,
	stamp: `Stamp`,
	viewblock: `Viewblock`,
	messageStamped: `Message Stamped`
};
