export const language = {
	appName: `Ping`,
	appDescription: `A decentralized messaging application built on top of <a href="https://arweave.org" target="_blank">Arweave</a>`,
	close: `Close`,
	connect: `Connect`,
	connectorNotFound: `Connector Not Found`,
	copyWalletAddress: `Copy Wallet Address`,
	copied: `Copied`,
	disconnect: `Disconnect`,
	fetching: `Fetching`,
	loading: `Loading`,
	message: (recipient: string) => `Message ${recipient}`,
	noMessages: `No Messages`,
	send: `Send`,
	sending: `Sending`,
	sendMessage: `Send Message`,
	groupSelect: `Select your group`,
	noGroupsFound: `You are not a part of any groups yet ! You can create a new group or join an existing group below.`,
	createGroup: `Create a new group`,
	title: `Title`,
	submit: `Submit`,
	logo: `Logo`,
	upload: `Upload`,
	uploadImage: `Upload Image`,
	initialChannel: `Initial Channel`,
	errorOccurred: `Error Occurred`,
	arweaveAppConnectionError: `Connection error with Arweave.app. The connector window must remain open after the initial connection.`,
	groupCreated: `Group Created`,
	addGroupMember: `Add Group Member`,
	createChannel: `Create a Channel`,
	walletAddress: `Wallet Address`,
	channelTitle: `Channel Title`,
	channelCreated: `Channel created`,
	memberAdded: `Member Added`,
	member: `Member`,
	members: `Members`,
	viewProfile: `View Profile`,
	profile: `Profile`,
	social: `Social`,
	twitter: `Twitter`,
	discord: `Discord`,
	groupId: `Group ID`,
	groupMembers: `Group Members`,
	stamp: `Stamp`,
	viewblock: `Viewblock`,
	messageStamped: `Message Stamped`,
	fetchingMessages: `Fetching Messages`,
	stampingMessage: `Stamping Message`,
	channelCreatedOn: `This channel was created on`,
	by: `by`,
	addLink: `Add Link`,
	add: `Add`,
	link: `Link`,
	cancel: `Cancel`,
	welcomeTo: `Welcome to`,
	walletConnectGroupView: `Connect your wallet to view your groups`,
	maxCharsReached: `Max Character Limit Reached`,
	handleBold: `Bold (Ctrl / Cmd + B)`,
	handleItalic: `Italic (Ctrl / Cmd + I)`,
	handleUnderline: `Underline (Ctrl / Cmd + U)`,
	handleCode: `Code (Ctrl / Cmd + C)`,
	messageSent: `Message Sent`,
	joinGroup: `Join a group`,
	setPrivateGroup: `Make this group Private. Private groups are only accessible via invite from other group members.`,
	groupJoined: `Group Joined`,
	groupJoinRestricted: `Private groups can only be joined via invite`,
	groupJoinExisting: `You are already a member of this group`,
	enterValidAddress: `Please enter a valid address`,
};
